version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html/:/var/www/html/
    depends_on:
      - php

  php:
    build: ./php
    container_name: "budget_php"
    volumes:
      - ./www/html/:/var/www/html/
    working_dir: /var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./.deploy/db/data:/var/lib/mysql
      - ./.deploy/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.deploy/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: budget
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root

  mail:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_PORT:-18025}:8025
